apiVersion: v1
kind: Secret
metadata:
  namespace: {{ namespace }}
  name: logstash-tls
type: Opaque
data:
{% macro inc(str) %}{% include str %}{% endmacro %}
  ca.key: {{ inc('secrets/ca.key') | b64encode }}
  ca.crt: {{ inc('secrets/ca.crt') | b64encode }}
  logstash.key: {{ inc('secrets/logstash.key') | b64encode }}
  logstash.crt: {{ inc('secrets/logstash.crt') | b64encode }}
